stages:
  - build
  - deploy
  - generate-signing-key

variables:
  REGISTRY: 486234852809.dkr.ecr.us-east-1.amazonaws.com
  SONATYPE_USERNAME: robot-datadog-serverless
  FORCE_TRIGGER:
    value: "false"
    description: "Set to true to override rules in the reliability-env pipeline (e.g. override 'only deploy master')"

.common: &common
  tags: [ "runner:main", "size:large" ]

cache: &default_cache
  key: '$CI_SERVER_VERSION' # Reset the cache every time gitlab is upgraded.  ~Every couple months
  paths:
    - .gradle/wrapper
    - .gradle/caches
  policy: pull

.gradle_build: &gradle_build
  <<: *common
  image: gradle:6.9.0-jdk8

build: &build
  <<: *gradle_build
  stage: build
  rules:
    - if: '$POPULATE_CACHE'
      when: never
    - when: on_success
  script:
    - ./gradlew clean build 
  artifacts:
    paths:
      - 'workspace/datadog-lambda-java/build/libs/*.jar'

build_with_cache:
  <<: *build
  rules:
    - if: '$POPULATE_CACHE'
      when: on_success
    - when: manual
      allow_failure: true
  cache:
    <<: *default_cache
    policy: push

deploy_to_sonatype:
  <<: *gradle_build
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*/'
      when: on_success
    - when: manual
      allow_failure: true
  script:
    - export SONATYPE_PASSWORD=$(aws ssm get-parameter --region us-east-1 --name ci.dd-trace-java.sonatype_password --with-decryption --query "Parameter.Value" --out text)
    - export GPG_PRIVATE_KEY=$(aws ssm get-parameter --region us-east-1 --name ci.dd-trace-java.signing.gpg_private_key --with-decryption --query "Parameter.Value" --out text)
    - export GPG_PASSWORD=$(aws ssm get-parameter --region us-east-1 --name ci.dd-trace-java.signing.gpg_passphrase --with-decryption --query "Parameter.Value" --out text)
    - ./gradlew -PbuildInfo.build.number=$CI_JOB_ID publishToSonatype closeSonatypeStagingRepository --max-workers=1 --build-cache --stacktrace --no-daemon

create_key:
  stage: generate-signing-key
  when: manual
  needs: []
  tags: [ "runner:docker", "size:large" ]
  variables:
    PROJECT_NAME: "datadog-lambda-java"
    EXPORT_TO_KEYSERVER: "true"
  image: $REGISTRY/ci/agent-key-management-tools/gpg:1
  script:
    - /create.sh
  artifacts:
    expire_in: 13 mos
    paths:
      - pubkeys
