variables:
  DOCKER_TARGET_IMAGE: registry.ddbuild.io/ci/datadog-lambda-java
  DOCKER_TARGET_VERSION: latest
  # Default version for development builds
  # This will be overwritten by the tag version if it is a release.
  VERSION: dev

stages:
  - pre
  - build

.go-cache: &go-cache
  key: datadog-lambda-java-go-cache
  policy: pull

ci image:
  stage: build
  image: registry.ddbuild.io/images/docker:20.10
  tags: ["arch:arm64"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - .gitlab/Dockerfile
      when: on_success
  variables:
    DOCKER_TARGET: ${DOCKER_TARGET_IMAGE}:${DOCKER_TARGET_VERSION}
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 --no-cache --pull --push --tag ${DOCKER_TARGET} -f .gitlab/Dockerfile .

generator:
  stage: pre
  image: registry.ddbuild.io/images/mirror/golang:alpine
  tags: ["arch:amd64"]
  cache: *go-cache
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /external_pull_request_event|merge_request_event|push/'
      when: never
    - when: always
  script:
    - if [[ "$CI_COMMIT_TAG" =~ ^v[0-9]+$ ]]; then echo "VERSION=${CI_COMMIT_TAG//[!0-9]/}" >> .env; fi
    - apk add --no-cache gomplate
    - gomplate --config .gitlab/config.yaml
  artifacts:
    paths:
      - .gitlab/build-pipeline.yaml
    reports:
      dotenv: .env

build:
  stage: build
  needs: ["generator"]
  trigger:
    include:
      - artifact: .gitlab/build-pipeline.yaml
        job: generator
    strategy: depend
  needs:
    - job: generator
      artifacts: true
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /external_pull_request_event|merge_request_event|push/'
      when: never
    - when: always
  variables:
    VERSION: $VERSION
