/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.datadoghq.datadog_lambda_layer_java;

import org.apache.logging

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
