package com.datadoghq.datadog_lambda_layer_java;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.apache.log4j.Level;
import org.apache.log4j.Logger;


public class Metrics {
    public void recordMetric() {
        Logger l = Logger.getLogger("datadog");
        l.log(Level.INFO, "foo");
    }
}
