/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.datadoghq.datadog_lambda_layer_java;

import org.junit.Test;
import static org.junit.Assert.*;

public class MetricsTest {
    @Test public void testSomeLibraryMethod() {
        DDMetric ddm = new DDMetric("foo", 24.3);
        assertEquals("{\"v\":24.3,\"m\":\"foo\"}", ddm.toJson());
    }
}
