name: Test on Main branch
on: 
        push:
                branches:
                        - main 
jobs:
  gradle:
    strategy:
      matrix:
        version: [8, 11]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.version }}
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 6.1.1
        arguments: test --info
