name: Run Gradle on PRs
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        version: [8, 11]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.version }}
    - uses: eskatos/gradle-command-action@v2
      with:
        gradle-version: 6.1.1
        arguments: test --info
